# Generated by Django 5.2.13 on 2026-04-14 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование категории')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='backend.partcategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория детали',
                'verbose_name_plural': 'Категории деталей',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('IPN', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Внутренний номер')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
                ('virtual', models.BooleanField(default=False, verbose_name='Виртуальная')),
                ('template', models.BooleanField(default=False, verbose_name='Шаблон')),
                ('assembly', models.BooleanField(default=False, verbose_name='Сборка')),
                ('component', models.BooleanField(default=True, verbose_name='Компонент')),
                ('revision', models.CharField(blank=True, max_length=20, null=True, verbose_name='Код ревизии')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('revision_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='backend.part', verbose_name='Ревизия из детали')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='backend.partcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Деталь',
                'verbose_name_plural': 'Детали',
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=5, default=0, max_digits=15, verbose_name='Количество на складе')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Местоположение')),
                ('batch', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер партии')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='backend.part', verbose_name='Деталь')),
            ],
            options={
                'verbose_name': 'Складской остаток',
                'verbose_name_plural': 'Складские остатки',
            },
        ),
        migrations.CreateModel(
            name='BomItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=5, default=1, max_digits=15, verbose_name='Количество')),
                ('optional', models.BooleanField(default=False, verbose_name='Опциональный')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('assembly', models.ForeignKey(help_text='Деталь, для которой указывается состав.', on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='backend.part', verbose_name='Сборка (родитель)')),
                ('sub_part', models.ForeignKey(help_text='Деталь, которая входит в состав сборки.', on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='backend.part', verbose_name='Компонент (подчинённая деталь)')),
            ],
            options={
                'verbose_name': 'Элемент спецификации (BOM)',
                'verbose_name_plural': 'Элементы спецификации (BOM)',
                'indexes': [models.Index(fields=['assembly'], name='idx_bom_assembly'), models.Index(fields=['sub_part'], name='idx_bom_sub_part')],
                'unique_together': {('assembly', 'sub_part')},
            },
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['category', 'active'], name='idx_part_category_active'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['IPN'], name='idx_part_ipn'),
        ),
    ]
